### ISSUE TITLE
Changing plot types window is cut off on Mac

### ISSUE THREAD

**Issue by installingrattle** [dreamRs/esquisse#22]
Thank you for an amazing package!

My window is cut off when I'm trying to change plot types. I've included a screenshot.

![image](https://user-images.githubusercontent.com/35076226/46567840-1a5a7c00-c97e-11e8-993e-c8c311a29ddf.png)

**Comment by installingrattle** [comment]
Here's another image to show how it's being cut off.

![image](https://user-images.githubusercontent.com/35076226/46567857-69a0ac80-c97e-11e8-8b34-0b815788676a.png)

**Comment by pvictor** [comment]
I added a scrollbar, this should be better, if you can install dev version and tell me if it works for you :)

```r
devtools::install_github("dreamRs/esquisse")
```

Victor

**Comment by GegznaV** [comment]
The problem is not related to Mac (or Windows, or etc.). The problem is **screen resolution and zooming** in RStudio. If you are using RStudio, make the zooming of all RStudio windows small enough (in RStudio v1.2 on Windows, I use <kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>-</kbd> to change the zooming, on Mac the shortcuts may be different) **before opening the shiny app**. If the zooming too big, some of the elements in the app may not fit into the app window. In this situation, you should **close** the app and zoom out. Then reopen the app and explore if the result satisfies you. **Note:** No desired effect will be achieved if the zooming is changed while the app is running.

When you finish your work with the app, reset the zooming to its previous state.

@installingrattle does this method help in your situation?

Related issues: #80 and possibly #17.

**Comment by opendatasurgeon** [comment]
Hi @GegznaV How are you sir? Unfortunately this issue is still present- even with the scroller present. Your workaround does work though. Thank you! I wish we didn't have to `Ctrl`+`+` and `Ctrl`+`-` .

![2021-04-12 125551](https://user-images.githubusercontent.com/47681434/114432442-b2a8cb80-9b8e-11eb-869f-ea20295e6511.jpg)
![Annotation 2021-04-12 125614](https://user-images.githubusercontent.com/47681434/114432440-b2103500-9b8e-11eb-92cd-e20d14609d0d.jpg)
